src/main/java/com/sptpc/domain/Reading.java
package com.sptpc.domain;

import java.util.Date;

public class Reading {
	private String ISBN ;
	private String bookName ;
	private String Author ;
	private Date BorrowDate ;
	private Date ReturnDate ;
	public String getISBN() {
		return ISBN;
	}
	public void setISBN(String iSBN) {
		ISBN = iSBN;
	}
	public String getBookName() {
		return bookName;
	}
	public void setBookName(String bookName) {
		this.bookName = bookName;
	}
	public String getAuthor() {
		return Author;
	}
	public void setAuthor(String Author) {
		this.Author = Author;
	}
	public Date getBorrowDate() {
		return BorrowDate;
	}
	public void setBorrowDate(Date borrowDate) {
		BorrowDate = borrowDate;
	}
	public Date getReturnDate() {
		return ReturnDate;
	}
	public void setReturnDate(Date returnDate) {
		ReturnDate = returnDate;
	}
	
}

src/main/java/com/sptpc/domain/Review.java
package com.sptpc.domain;

public class Review {
    private int ID ;
    private String ISBN;
    private String ReaderID;
    private String Grade;
    private String Talk;

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getISBN() {
        return ISBN;
    }

    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }

    public String getReaderID() {
        return ReaderID;
    }

    public void setReaderID(String readerID) {
        ReaderID = readerID;
    }

    public String getGrade() {
        return Grade;
    }

    public void setGrade(String grade) {
        Grade = grade;
    }

    public String getTalk() {
        return Talk;
    }

    public void setTalk(String talk) {
        Talk = talk;
    }
}

src/main/webapp/WEB-INF/jsp/admin-checkBook.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>  
  <head>
    <meta charset="UTF-8">
    <title>查询</title>
      <meta name="renderer" content="webkit">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
      <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
      <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
      <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
      <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
  </head>
  
  <body>
    <div class="x-body">      
      <table class="layui-table">
        <thead>
          <tr>
            <th>IBSN</th>
            <th>图书名称</th>
            <th>读者ID</th>
            <th>读者名称</th>
            <th>借书日期</th>
            <th>还书日期</th>
            <th>剩余数量</th>
            <th>当前状态</th>
            <th >操作</th>
            </tr>
        </thead>
        <tbody>
        <c:forEach items="${bookList}" var="book" >
          <tr>
              <td>${book.ISBN}</td>
              <td>${book.bookName}</td>
              <td>${book.readerID}</td>
              <td>${book.readerName}</td>
              <td>${book.borrowDate}</td>
              <td>${book.returnDate}</td>
              <td>${book.count}</td>
              <td>${book.state}</td>
            <td>
            	<a title="通过审核" href="/admin/checkBook?bid=${book.ISBN}&uid=${book.readerID}">
                <i class="layui-icon">&#xe618;</i>通过审核
        		</a>
        		<a title="取消借阅" style="margin-left: 20px" href="/admin/cancelBook?bid=${book.ISBN}&uid=${book.readerID}">
                <i class="layui-icon">&#xe640;</i>取消借阅
              </a>
            </td>            
          </tr>
<%--          <%--%>
<%--        		}--%>
<%--        	}--%>
<%--          %>--%>
        </c:forEach>
        </tbody>
      </table>
    </div>   
  </body>
</html>

src/main/webapp/WEB-INF/jsp/admin-home.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>后台系统管理</title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
    <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>

</head>
<body>
<%--<%--%>
<%--	Reader reader = (Reader)session.getAttribute("admin");--%>
<%--%>--%>
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo"><a href="index.html">图书管理系统</a></div>
        <div class="left_open">
            <i title="展开左侧栏" class="iconfont">&#xe699;</i>
        </div>  
        <ul class="layui-nav right" lay-filter="">
        	<li class="layui-nav-item">
        		<a href="#">欢迎你,管理员：${session_reader.readerName}</a>
        	</li>
        	<li class="layui-nav-item">
        		<a href="/user/back.do">退出登录</a>
        	</li>
        </ul>
        
    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
     <!-- 左侧菜单开始 -->
    <div class="left-nav">
      <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe6b8;</i>
                    <cite>个人管理</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="/resetList">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>修改信息</cite>
                            
                        </a>
                    </li >
                    <li>
                        <a _href="/user/deletReader">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>注销账户</cite>

                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe723;</i>
                    <cite>用户管理</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="/admin/userList">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>用户列表</cite>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe726;</i>
                    <cite>图书管理</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="/admin/returnAddBook">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>图书上架</cite>
                        </a>
                    </li >
                    <li>
                        <a _href="/admin/checkBookList">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>审核借书</cite>
                        </a>
                    </li >
                    <li>
                        <a _href="/admin/returnBookList">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>审核还书</cite>
                        </a>
                    </li >
                    <li>
                        <a _href="/admin/bookList">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>图书库存</cite>
                        </a>
                    </li >
                </ul>
            </li>           
        </ul>
      </div>
    </div>
    <!-- <div class="x-slide_left"></div> -->
    <!-- 左侧菜单结束 -->
    <!-- 右侧主体开始 -->
    <div class="page-content">
        <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
          <ul class="layui-tab-title">
            <li>我的桌面</li>
          </ul>
          <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <iframe src='/welcome.do' frameborder="0" scrolling="yes" class="x-iframe"></iframe>
            </div>
          </div>
        </div>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
    <!-- 底部开始 -->
    <div class="footer">
        <div class="copyright">Copyright ©2019 第一小组</div>
    </div>
    <!-- 底部结束 -->
    
</body>
</html>

src/main/webapp/WEB-INF/jsp/admin-resetUser.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin2.0</title>
      <meta name="renderer" content="webkit">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
      <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
      <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
      <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
      <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<%-- <%--%>
<%--	Reader reader = (Reader)session.getAttribute("rId");--%>
<%--%>--%>
  <body>
    <div class="x-body">
        <form class="layui-form" action="/admin/readerReset" method="post" >
          <div class="layui-form-item">
              <label for="L_email" class="layui-form-label">
                  <span class="x-red">*</span>账号
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_email" name="uid" required="" lay-verify="nikename"
                  autocomplete="off" class="layui-input" value="${reader.readerId}" readonly="">
              </div>
              <div class="layui-form-mid layui-word-aux">
                  <span class="x-red">*</span>您唯一的登入账号,不可修改
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_username" class="layui-form-label">
                  <span class="x-red">*</span>用户名称
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_username" name="username" required="" lay-verify="nikename"
                  autocomplete="off" class="layui-input" value="${reader.readerName}">
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_username" class="layui-form-label">
                  <span class="x-red">*</span>系别
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_username" name="dept" required="" lay-verify="nikename"
                  autocomplete="off" class="layui-input" value="${reader.readerDept}">
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_username" class="layui-form-label">
                  <span class="x-red">*</span>电话
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_username" name="phone" required="" lay-verify="nikename"
                  autocomplete="off" class="layui-input" value="${reader.readerPhone}">
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
              </label>
              <button  class="layui-btn" lay-filter="add" lay-submit="">
                  修改
              </button> 
              <!-- <input value="修改" lay-submit lay-filter="register" style="width:100%;" type="submit"> -->
          </div>
      </form>
    </div>
  </body>

</html>

src/main/webapp/WEB-INF/jsp/admin-userList.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>  
  <head>
    <meta charset="UTF-8">
    <title>用户列表</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
    <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
  </head>
  
  <body>
    <div class="x-body">      
      <table class="layui-table">
        <thead>
          <tr>
            <th>
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>用户ID</th>
            <th>用户姓名</th>
            <th>用户系别</th>
            <th>用户电话</th>
            <th >操作</th>
            </tr>
        </thead>
        <tbody>
        <c:forEach items="${reader}" var="rd" >
          <tr>
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>${rd.readerId}</td>
            <td>${rd.readerName}</td>
            <td>${rd.readerDept}</td>
            <td>${rd.readerPhone}</td>
            <td class="td-manage">
              <a title="修改信息" href="/admin/sendId?id=${rd.readerId}&name=${rd.readerName}&dept=${rd.readerDept}&phone=${rd.readerPhone}">
                <i class="layui-icon">&#xe618;</i>修改信息
              </a>
              <a title="删除用户" style="margin-left: 20px;" href="/admin/delUser?id=${rd.readerId}">
                <i class="layui-icon">&#xe640;</i>删除用户
              </a>
              <a title="设为管理员" style="margin-left: 20px;" href="/admin/addAdmin?id=${rd.readerId}">
                <i class="layui-icon">&#xe642;</i>设为管理员
              </a>
            </td>
          </tr>
        </c:forEach>
        </tbody>
      </table>
    </div>   
  </body>
</html>

src/main/webapp/WEB-INF/jsp/book-list.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>在线书房</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
    <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
  </head>
  
  <body>
<%--<%--%>
<%--	Reader reader = (Reader)session.getAttribute("reader");--%>
<%--%>--%>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so" action="/book/search" method="post" >
          <input type="text" name="bookName"  placeholder="请输入图书名称" autocomplete="off" class="layui-input">
         <button class="layui-btn"  lay-submit="" lay-filter="sreach" type="submit"><i class="layui-icon">&#xe615;</i></button> 
         <!-- <input value="搜索" lay-submit  style="width:10%;" type="submit"> -->
        </form>
      </div>
      <table class="layui-table">
        <thead>
          <tr>
            <th>
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>IBSN</th>
            <th>图书类别</th>
            <th>读书名称</th>
            <th>作者</th>
            <th>出版社</th>
            <th>图书单价</th>
            <th>剩余数量</th>
            <th >操作</th>
            </tr>
        </thead>
        <tbody>
          <c:forEach items="${book}" var="book" >
          <tr>
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>${book.ISBN}</td>
            <td>${book.typeID}</td>
            <td>${book.bookName}</td>
            <td>${book.author}</td>
            <td>${book.publish}</td>
            <td>${book.unitPrice}</td>
            <td>${book.count}</td>
            <td class="td-manage">
              <a title="我要预约" href="/book/booking?uid=${session_reader.readerId}&bid=${book.ISBN}">
                <i class="layui-icon">&#xe63c;</i>我要预约
              </a>
            </td>
          </tr>
          </c:forEach>
        </tbody>
      </table>
  </body>

</html>

src/main/webapp/WEB-INF/jsp/comReview.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>  
  <head>
    <meta charset="UTF-8">
    <title>在线书房</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
    <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
    <style type="text/css">
    .layui-table td, .layui-table th{
    	width: 20%;
    }
    </style>
  </head>
  
  <body>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so" action="/user/searchReview" method="post" >
          <input type="text" name="bookName"  placeholder="请输入图书名称" autocomplete="off" class="layui-input">
         <button class="layui-btn"  lay-submit="" lay-filter="sreach" type="submit"><i class="layui-icon">&#xe615;</i></button> 
         <!-- <input value="搜索" lay-submit  style="width:10%;" type="submit"> -->
        </form>
      </div>
      <table class="layui-table">
        <thead>
          <tr>
            <th>评论用户</th>
            <th>IBSN</th>
            <th>图书名称</th>            
            <th>评分</th>
            <th>书评</th>
            </tr>
        </thead>
        <tbody>
        <c:forEach items="${review}" var="review" >
          <tr>
            <td>${review.readerName}</td>
            <td>${review.ISBN}</td>
            <td>${review.bookName}</td>
            <td>${review.grade} 分</td>
            <td>${review.talk}</td>
          </tr>
        </c:forEach>
        </tbody>
      </table>
  </body>
</html>

src/main/webapp/WEB-INF/jsp/deletReader.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
  
  <head>
      <meta charset="UTF-8">
      <title>后台系统管理</title>
      <meta name="renderer" content="webkit|ie-comp|ie-stand">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
      <meta http-equiv="Cache-Control" content="no-siteapp" />

      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
      <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
      <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
      <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
      <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
    <![endif]-->
  </head>
  
  <body>

    <div class="x-body">
        <form class="layui-form" action="/user/delReader" method="post" >
          <div class="layui-form-item">
              <label for="L_pass" class="layui-form-label">
                  <span class="x-red">*</span>密码
              </label>
              <input style="display: none " name="uid" value="${session_reader.readerId}"/>
              <div class="layui-input-inline">
                  <input type="password" id="L_pass" name="pass" required="" lay-verify="pass"
                  autocomplete="off" class="layui-input"/>
              </div>
              <div class="layui-form-mid layui-word-aux">
                  
              </div>
          </div>
          <div class="layui-form-item">
              <button  class="layui-btn" lay-filter="add" lay-submit="">
                  注销
              </button>
          </div>
      </form>
    </div>
  </body>

</html>

src/main/webapp/WEB-INF/jsp/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<jsp:forward page="login.jsp"></jsp:forward>

src/main/webapp/WEB-INF/jsp/state.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@page import="java.util.List"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>  
  <head>
    <meta charset="UTF-8">
    <title>查询</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/font.css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/xadmin.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
    <script src="${pageContext.request.contextPath}/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/xadmin.js"></script>
  </head>
  
  <body>
    <div class="x-body">      
      <table class="layui-table">
        <thead>
          <tr>
            <th>
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>IBSN</th>
            <th>图书类别</th>
            <th>读书名称</th>
            <th>作者</th>
            <th>出版社</th>
            <th>图书单价</th>
            <th>剩余数量</th>
            <th >当前状态</th>
            </tr>
        </thead>
        <tbody>
<%--           <%--%>
<%--        	List list = (List)session.getAttribute("state");--%>
<%--        	if(list == null){--%>
<%--        %>--%>
<%--        null--%>
<%--        <%--%>
<%--        	}else{--%>
<%--        		for(int i = 0 ; i < list.size() ; i++){--%>
<%--        			BorrowBook bb = (BorrowBook)list.get(i);        		--%>
<%--        %>--%>
          <c:forEach items="${book}" var="book" >
          <tr>
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>${book.ISBN}</td>
            <td>${book.typeName}</td>
            <td>${book.bookName}</td>
            <td>${book.author}</td>
            <td>${book.publish}</td>
            <td>${book.unitPrice}</td>
            <td>${book.count}</td>
            <td>${book.state}</td>
          </tr>
          </c:forEach>
        </tbody>
      </table>
    </div>   
  </body>
</html>